// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DAL.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DAL.Data
{
    public partial class FormationOumdinAcademyContext
    {
        private IFormationOumdinAcademyContextProcedures _procedures;

        public virtual IFormationOumdinAcademyContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new FormationOumdinAcademyContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IFormationOumdinAcademyContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PS_CommandeResult>().HasNoKey().ToView(null);
        }
    }

    public partial class FormationOumdinAcademyContextProcedures : IFormationOumdinAcademyContextProcedures
    {
        private readonly FormationOumdinAcademyContext _context;

        public FormationOumdinAcademyContextProcedures(FormationOumdinAcademyContext context)
        {
            _context = context;
        }

        public virtual async Task<List<PS_CommandeResult>> PS_CommandeAsync(DateTime? dataCommande, int? idCommande, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "dataCommande",
                    Value = dataCommande ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "idCommande",
                    Value = idCommande ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<PS_CommandeResult>("EXEC @returnValue = [dbo].[PS_Commande] @dataCommande, @idCommande", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
