// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DAL.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DAL.Data
{
    public partial interface IFormationOumdinAcademyContextProcedures
    {
        Task<List<PS_CommandeResult>> PS_CommandeAsync(DateTime? dataCommande, int? idCommande, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
