// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class PS_CommandeResult
    {
        public int id { get; set; }
        public DateTime? dateCommande { get; set; }
        public int? _idClient { get; set; }
        public int? etatCommande { get; set; }
        public decimal? totalHT { get; set; }
    }
}
