// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class TBonCommande
{
    public int Id { get; set; }

    public DateTime? DateCommande { get; set; }

    public int? IdClient { get; set; }

    public int? EtatCommande { get; set; }

    public decimal? TotalHt { get; set; }

    public virtual TClient IdClientNavigation { get; set; }

    public virtual ICollection<TDetailCommande> TDetailCommande { get; } = new List<TDetailCommande>();
}