// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class TCategorie
{
    public int Id { get; set; }

    public string Categorie { get; set; }

    public virtual ICollection<TProduit> TProduit { get; } = new List<TProduit>();
}