// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class TClient
{
    public int Id { get; set; }

    public string Client { get; set; }

    public string Adresse { get; set; }

    public virtual ICollection<TBonCommande> TBonCommande { get; } = new List<TBonCommande>();
}