// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class VCommande
{
    public string Client { get; set; }

    public DateTime? DateCommande { get; set; }

    public int? EtatCommande { get; set; }

    public decimal? TotalHt { get; set; }

    public decimal? Qnt { get; set; }

    public decimal? PrixUnitaire { get; set; }

    public decimal? Total { get; set; }
}